export const initialItems = [
  {
    h: 8,
    i: '1740229111459',
    w: 3,
    x: 0,
    y: 0,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'vertical',
    background: '',
    showPreview: false,
  },
  {
    h: 8,
    i: '1740229111421',
    w: 6,
    x: 3,
    y: 2,
    type: 'pseudoImageCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    caption: 'My Photography',
    sizeKey: 'doubleHorizontal',
    background: '',
  },
  {
    h: 4,
    i: '1740229818445',
    w: 3,
    x: 9,
    y: 0,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'square',
    background: '',
    showPreview: false,
  },
  {
    h: 4,
    i: '1740229819513',
    w: 3,
    x: 0,
    y: 8,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'square',
    background: '',
    showPreview: false,
  },
  {
    h: 8,
    i: '1740229847094',
    w: 3,
    x: 9,
    y: 4,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'vertical',
    background: '',
    showPreview: false,
  },
  {
    h: 2,
    i: '1740229855859',
    w: 6,
    x: 3,
    y: 0,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'halfHorizontal',
    background: '',
    showPreview: false,
  },
  {
    h: 2,
    i: '1740230287231',
    w: 6,
    x: 3,
    y: 10,
    type: 'text',
    content: 'Explore more components using your dock ⬇️\n',
    sizeKey: 'medium',
    background: '',
  },
];

export const initialMobileItems = [
  {
    h: 10,
    i: '1740229111459',
    w: 1,
    x: 0,
    y: 2,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'vertical',
    background: '',
    showPreview: false,
  },
  {
    h: 8,
    i: '1740229111421',
    w: 2,
    x: 0,
    y: 12,
    type: 'pseudoImageCard',
    displayImage:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    caption: 'My Photography',
    sizeKey: 'doubleHorizontal',
  },
  {
    h: 5,
    i: '1740229818445',
    w: 1,
    x: 1,
    y: 2,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'square',
    background: '',
    showPreview: false,
  },
  {
    h: 5,
    i: '1740229819513',
    w: 1,
    x: 1,
    y: 7,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'square',
    background: '',
    showPreview: false,
  },
  {
    h: 4,
    i: '1740229847094',
    w: 2,
    x: 0,
    y: 20,
    type: 'pseudoUrlCard',
    image:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'horizontal',
    background: '',
    showPreview: false,
  },
  {
    h: 2,
    i: '1740229855859',
    w: 2,
    x: 0,
    y: 0,
    type: 'pseudoUrlCard',
    displayImage:
      'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png',
    sizeKey: 'halfHorizontal',
    background: '',
    showPreview: false,
  },
  {
    h: 2,
    i: '1740230287231',
    w: 2,
    x: 0,
    y: 24,
    type: 'text',
    content: 'Explore more components using your dock ⬇️\n',
    sizeKey: 'medium',
    background: '',
  },
];

export const initialTheme = {
  name: 'Light',
  color: '#ffffff',
  border: '#e5e5e5',
  textMode: 'dark',
  background: '#ffffff',
  cardBackground: '#f7f7f7',
};
