export const itemsRightPanel = [
  {
    id: '1',
    image: '/MoreComponentsIcons/forms.svg',
    title: 'Custom form',
    type: 'formCard',
    sizeKey: 'square',
    isPremium: true,
    content: {
      caption: 'No form chosen',
      background: '',
      showPreview: false,
      formId: '',
      image: '',
    },
  },
  {
    id: '2',
    image: '/MoreComponentsIcons/shoppableCard.svg',
    title: 'Shopping Card',
    sizeKey: 'vertical',
    type: 'shopCard',
  },
  {
    id: '3',
    image: '/MoreComponentsIcons/calendar.svg',
    title: 'Calendar Card',
    sizeKey: 'vertical',
    type: 'calendarCard',
    isPremium: true,
  },
  {
    id: '4',
    image: '/MoreComponentsIcons/maps.png',
    title: 'Map Card',
    sizeKey: 'square',
    type: 'mapCard',
    isPremium: true,
    content: {
      location: '',
      mapUrl: '',
      title: '',
      mapStyle: 'roadmap',
      showPingAnimation: true,
      showClouds: true,
      showFlightPath: true,
      autoAnimations: true,
    },
  },
  {
    id: '5',
    image: '/MoreComponentsIcons/youtube.webp',
    title: 'YouTube Card',
    sizeKey: 'doubleHorizontal',
    type: 'youtubeCard',
    content: {
      link: '',
      caption: '',
      background: '',
    },
  },
  {
    id: '7',
    image: '/MoreComponentsIcons/drive.webp',
    title: 'Google Drive Card',
    sizeKey: 'horizontal',
    type: 'driveCard',
    isPremium: true,
    content: {
      link: '',
      caption: '',
      viewMode: 'preview',
      showCaptions: true,
    },
  },
  {
    id: '8',
    image: '/MoreComponentsIcons/counter.png',
    title: 'Counter Card',
    sizeKey: 'square',
    type: 'counterCard',
    isPremium: true,
    content: {
      title: 'Satisfied Customers',
      subtitle: 'and counting',
      targetValue: 1000,
      startValue: 0,
      direction: 'up',
      decimalPlaces: 0,
      delay: 0,
      duration: 2000,
      autoRestart: false,
      restartInterval: 5,
      textColor: '#000000',
      background: '#FFFFFF',
      titleColor: '#000000',
      subtitleColor: '#666666',
      isVisible: true,
    },
  },
  {
    id: '9',
    image: '/MoreComponentsIcons/countdown-timer.png',
    title: 'Countdown Timer',
    sizeKey: 'square',
    type: 'countdownTimerCard',
    isPremium: true,
    content: {
      title: 'Sale Ends In',
      subtitle: "Don't miss out!",
      days: 3,
      hours: 0,
      minutes: 0,
      seconds: 0,
      isVisible: true,
    },
  },
  {
    id: '10',
    image: '/MoreComponentsIcons/componentCarousel.png',
    title: 'Image Carousel',
    sizeKey: 'fullCarousel',
    type: 'carouselCard',
    isPremium: true,
    content: {
      scrollSpeed: 300,
      autoScroll: false,
      autoScrollInterval: 5000,
      itemsPerSlide: 1,
      carouselItems: [],
    },
  },
  {
    id: '11',
    image: '/MoreComponentsIcons/marquee.svg',
    title: 'Marquee',
    description: 'Add an infinite scrolling marquee',
    type: 'marquee',
    sizeKey: 'fullMarquee',
    isPremium: true,
    content: {
      speed: 40,
      gap: 20,
      direction: 'left',
      pauseOnHover: false,
      title: '',
      marqueeItems: [],
    },
  },
  {
    id: '12',
    image: '/MoreComponentsIcons/testimonials.svg',
    title: 'Testimonials Slider',
    sizeKey: 'fullMarquee',
    type: 'testimonials',
    isPremium: true,
    content: {
      scrollSpeed: 300,
      autoScroll: true,
      autoScrollInterval: 5000,
      effect: 'slide',
      testimonials: [],
    },
  },
  {
    id: '13',
    image: '/MoreComponentsIcons/banner.png',
    title: 'Banner Card',
    sizeKey: 'banner',
    type: 'bannerCard',
    content: {
      link: '',
      caption: '',
      background: '',
    },
  },
  {
    id: '13',
    image: '/MoreComponentsIcons/reelCard.png',
    title: 'IG Reel Card',
    sizeKey: 'vertical',
    type: 'instagramReelCard',
    content: {
      link: '',
      caption: '',
      background: '',
    },
  },
];
