export const defaultItems = [
  {
    h: 3,
    i: '1747654344424',
    w: 3,
    x: 6,
    y: 8,
    type: 'mapCard',
    zoom: 13,
    title: '',
    mapUrl: '',
    sizeKey: 'square',
    location: '',
    mapStyle: 'roadmap',
    showClouds: true,
    coordinates: {
      lat: 40.7128,
      lng: -74.006,
    },
    autoAnimations: true,
    showFlightPath: true,
    cardThemeBright: false,
    showPingAnimation: true,
  },
  {
    h: 6,
    i: '1747654716181',
    w: 6,
    x: 6,
    y: 0,
    link: null,
    type: 'image',
    image: 'https://pocketlink.co/landingpage/discordLandscape.png',
    caption: 'Welcome to pocketlink!',
    sizeKey: 'doubleHorizontal',
    cardThemeBright: false,
  },
];

export const defaultMobileItems = [
  {
    h: 4,
    i: '1747654344424',
    w: 1,
    x: 0,
    y: 10,
    type: 'mapCard',
    zoom: 13,
    title: '',
    mapUrl: '',
    sizeKey: 'square',
    location: '',
    mapStyle: 'roadmap',
    showClouds: true,
    coordinates: {
      lat: 40.7128,
      lng: -74.006,
    },
    autoAnimations: true,
    showFlightPath: true,
    cardThemeBright: false,
    showPingAnimation: true,
  },
  {
    h: 8,
    i: '1747654716181',
    w: 2,
    x: 0,
    y: 0,
    link: null,
    type: 'image',
    image: 'https://pocketlink.co/landingpage/discordLandscape.png',
    caption: 'Welcome to pocketlink!',
    sizeKey: 'doubleHorizontal',
    cardThemeBright: false,
  },
];

export const defaultTheme = {
  name: 'Light',
  color: '#ffffff',
  border: '#e5e5e5',
  textMode: 'dark',
  background: '#ffffff',
  cardBackground: '#f0f0ed',
};
