import { GoogleGenerativeAI } from '@google/generative-ai';
import { jsonrepair } from 'jsonrepair';
import { AIComponentTreeGenerationKnowledge } from '@/constants/AIBuillder/AIComponentTreeGenerationKnowledge';

// Initialize Gemini API with Fixer Agent API key
const genAI = new GoogleGenerativeAI(
  process.env.NEXT_PUBLIC_FIXER_AGENT_ENGINE_ID
);
const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

/**
 * Fixer Agent
 *
 * Responsibilities:
 * 1. Verify and fix component sizes based on AI Component Tree Generation Knowledge
 * 2. Ensure mobile and desktop layouts have proper grid alignment
 * 3. Fix any spacing or positioning issues
 * 4. Optimize the layout for visual appeal and balance
 * 5. Ensure all components have appropriate content fields
 */
export async function fixerAgent(builderOutput) {
  console.log('🔧 [Fixer] Starting layout verification and optimization...');

  try {
    if (!builderOutput || !builderOutput.success || !builderOutput.data) {
      console.error('❌ [Fixer] Missing or invalid builder output');
      return {
        success: false,
        error: 'Missing or invalid builder output',
        data: null,
      };
    }

    const data = builderOutput.data;

    // Extract layout data from builder output
    const { items = [], mobileItems = [], theme = {}, layoutPlan = '' } = data;

    // Log extracted data for debugging
    console.log(
      `🔧 [Fixer] Analyzing layout with ${items.length} desktop items and ${mobileItems.length} mobile items`
    );

    // System prompt for the Fixer
    const systemPrompt = `
You are the Fixer Agent for PocketLink's Onboarding Layout Generator.

Your task is to verify and optimize the layout generated by the Builder Agent, ensuring all components
have the correct sizes and positioning according to the AI Component Tree Generation Knowledge.

Guidelines:
1. Verify that all components use the correct size keys for their type
2. Ensure the desktop layout uses the 12-column grid system correctly
3. Ensure the mobile layout uses the 2-column grid system correctly
4. Fix any spacing or positioning issues to create a balanced layout
5. Optimize the layout for visual appeal and usability
6. Verify that all components have the appropriate content fields
7. Do not change the overall structure or content of the layout unless necessary for fixes
8. Strictly follow the AIComponentTreeGenerationKnowledge for component sizing and layout principles

Key Size Key Compatibility Rules to Enforce:
- url, image, video, nestedCard, text: square, vertical, halfHorizontal, horizontal, doubleHorizontal
- youtubeCard: vertical, horizontal, doubleHorizontal
- mapCard: square, vertical, horizontal, doubleHorizontal
- carouselCard: square, vertical, horizontal, doubleHorizontal, fullCarousel
- testimonialsCard: doubleHorizontal, fullCarousel
- spotifyCard: horizontal, doubleHorizontal
- driveCard: doubleHorizontal
- counterCard, countdownTimerCard: square, vertical, horizontal, doubleHorizontal
- bannerCard: banner
- shopCard, formCard, calendarCard: square, vertical, doubleHorizontal
- section title: wider, full

SIZE KEY DIMENSIONS:
For desktop:
- square: w:3, h:4
- vertical: w:3, h:8
- horizontal: w:6, h:4
- doubleHorizontal: w:6, h:8
- halfHorizontal: w:6, h:2
- wider: w:6, h:2.25
- full: w:12, h:2.25
- fullCarousel: w:12, h:8
- banner: w:12, h:4

For mobile:
- square: w:1, h:5
- vertical: w:1, h:10
- horizontal: w:2, h:4
- doubleHorizontal: w:2, h:8
- halfHorizontal: w:2, h:2
- wider: w:2, h:2.25
- full: w:2, h:2.25
- fullCarousel: w:2, h:8
- banner: w:2, h:4
`;

    // User prompt with layout data
    const userPrompt = `
COMPONENT TREE GENERATION KNOWLEDGE:
${AIComponentTreeGenerationKnowledge}

DESKTOP ITEMS (${items.length}):
${JSON.stringify(items, null, 2)}

MOBILE ITEMS (${mobileItems.length}):
${JSON.stringify(mobileItems, null, 2)}

THEME:
${JSON.stringify(theme, null, 2)}

LAYOUT PLAN:
${layoutPlan}

Please analyze this layout and make the following corrections, referring explicitly to the AIComponentTreeGenerationKnowledge:

1. Fix any components that have incorrect size keys for their type
2. Ensure all desktop components correctly follow the 12-column grid (w: 1-12)
3. Ensure all mobile components correctly follow the 2-column grid (w: 1-2)
4. Verify the x, y, w, h values based on the sizeKey specification
5. Fix any spacing issues or overlapping components
6. Ensure all components have the required content fields for their type
7. Optimize the layout for visual balance and appeal
8. Apply the audience-specific layout guidelines from AIComponentTreeGenerationKnowledge

Return your response in the following JSON format:

{
  "layoutPlan": "Explanation of the layout optimizations made",
  "items": [
    // Fixed and optimized desktop items
  ],
  "mobileItems": [
    // Fixed and optimized mobile items
  ],
  "theme": {
    // Unchanged theme data
  },
  "fixes": [
    "Description of fix 1",
    "Description of fix 2"
  ]
}
`;

    console.log('🔮 [Fixer] Calling Gemini API for layout optimization...');

    // Call Gemini API with the prompt
    const fixerResult = await model.generateContent([
      { role: 'system', parts: [{ text: systemPrompt }] },
      { role: 'user', parts: [{ text: userPrompt }] },
    ]);

    const fixerResponse = await fixerResult.response;
    const fixerText = fixerResponse.text();

    console.log(
      `📄 [Fixer] Layout optimization response length: ${fixerText.length} characters`
    );

    // Extract JSON from the response
    let optimizedLayout;
    try {
      // Find JSON in the response
      const jsonStartIndex = fixerText.indexOf('{');
      const jsonEndIndex = fixerText.lastIndexOf('}') + 1;

      if (jsonStartIndex === -1 || jsonEndIndex <= 0) {
        throw new Error('Invalid response format - no JSON found');
      }

      const jsonStr = fixerText.substring(jsonStartIndex, jsonEndIndex);
      const repairedJson = jsonrepair(jsonStr);
      optimizedLayout = JSON.parse(repairedJson);

      console.log('✅ [Fixer] Layout optimization successful');
      console.log(
        `📊 [Fixer] Made ${optimizedLayout.fixes?.length || 0} fixes to the layout`
      );

      // Return optimized layout with fixes
      return {
        success: true,
        data: {
          items: optimizedLayout.items || items,
          mobileItems: optimizedLayout.mobileItems || mobileItems,
          theme: optimizedLayout.theme || theme,
          fixes: optimizedLayout.fixes || [],
          layoutPlan: optimizedLayout.layoutPlan || layoutPlan,
        },
      };
    } catch (error) {
      console.error('❌ [Fixer] Error optimizing layout:', error);

      // Return the original data if there was an error
      return {
        success: true,
        error: error.message || 'Failed to optimize layout, using original',
        data: {
          items: items,
          mobileItems: mobileItems,
          theme: theme,
          layoutPlan: layoutPlan,
        },
      };
    }
  } catch (error) {
    console.error('❌ [Fixer] Unhandled error:', error);

    return {
      success: false,
      error: error.message || 'Internal server error',
      details: error.stack,
    };
  }
}
